[build]
  command = "npm run build" # The build command to run
  publish = "dist"           # Directory where the built files are stored (update if different)

[context.production.environment]
  NODE_ENV = "production"
